version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  lint:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm install
      - lint:
          requires:
            - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          start: npm run dev
          wait-on: http://localhost:3000
          group: all tests
          command: npm run test_ci
          # parallel: true
          # parallelism: 10
          post-steps:
            - store_test_results:
                path: cypress/results
